
- name: show groups list
  debug: msg="groups - {{ default_groups }}"

- name: Ensure required groups exist on VM
  delegate_to: localhost
  become: false
  vars:
    group_list: "{{ default_groups | map('regex_replace', '^\"|\"$', '') | list }}"
  shell: |
    ssh -o BatchMode=yes \
        -o UserKnownHostsFile=/dev/null \
        -o StrictHostKeyChecking=no \
        -o ConnectTimeout=5 \
        {{ admin_id }}@{{ vm_fqdn }} '
        for grp in {{ group_list | join(" ") }}; do
          getent group "$grp" || sudo groupadd "$grp"
        done
        '
