# stage one existence
- name: Set fact for existing VMs
  set_fact:
    vm_host: "{{ inventory_hostname }}"
    vm_fqdn: >-
      {{ hostvars[inventory_hostname].ansible_fqdn
        | default(inventory_hostname + '.' + (ansible_domain | default(lookup('env', 'ipa_domain'))) ) }}

- name: check ips status
  import_tasks: check_system.yml
  when: force_rebuild is not defined or force_rebuild is false

- name: update global_vm_build_state
  set_fact:
    global_vm_build_state: "{{ vm_build_stage }}"
  when: force_rebuild is not defined or force_rebuild is false

- name: Process new systems 
  when: vm_build_stage not in ["scanned","ready","compliant"]
  block: 
    - name: Check if VM exists
      become: yes
      delegate_to: "{{ kvm_delegate }}"
      import_tasks: prep_stage.yml
      when: 
      - "'kvm' not in group_names"

    - name: Check if VM exists
      become: yes
      delegate_to: "{{ kvm_delegate }}"
      import_tasks: stage_one.yml
      when: 
      - "'kvm' not in group_names"

    - name: Start and get status
      become: yes
      delegate_to: "{{ kvm_delegate }}"
      import_tasks: stage_two.yml
      when: 
      - "'kvm' not in group_names"

    - name: vm_build_state status
      debug:
        msg: "vm_build_state is {{ vm_build_state }}"
      when: 
      - "'kvm' not in group_names"

    - name: Start and get status
      become: yes
      delegate_to: "{{ kvm_delegate }}"
      import_tasks: stage_three.yml
      when: 
      - "'kvm' not in group_names"
      - vm_build_state == "sshok"

    - name: Manually add my ssh key to secops authorized_keys
      become: false
      shell: |
        ssh-copy-id -o BatchMode=yes \
            -o UserKnownHostsFile=/dev/null \
            -o StrictHostKeyChecking=no \
            -o ConnectTimeout=5 \
            {{ admin_id }}@{{ vm_fqdn }}
      vars:
        ansible_user: "{{ admin_id }}"
        ansible_ssh_pass: "{{ admin_set }}"
        ansible_host: "{{ vm_fqdn }}"
      delegate_to: "localhost"
      when: 
      - vm_build_state == "sshok"

    - name: Show build stage main
      debug:
        msg: "System is in stage:  {{ vm_build_state }}"
      when: 
      - "'kvm' not in group_names"

    - name: Promote vm_build_state to global_vm_build_state
      set_fact:
        global_vm_build_state: "{{ vm_build_state }}"
  