- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: show status before next check
  debug:
    msg: "vm_build_state {{vm_build_state}}, vm_timeout {{vm_timeout}}"

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: 
    - vm_build_state != "shutdown" 
    - (vm_timeout | int) < shutdown_max_timeout

- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: Wait before next check
  wait_for:
    timeout: 60
  delegate_to: localhost
  become: false
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout
