  # roles/kvm_provision/tasks/start_vm.yml

- name: Start VMs in dependency order
  include_tasks: vm_boot_order.yml
  vars:
    ordered_groups: ['ca','ca_intermediate','helpers', 'dns']
  when: vm_build_state != "running"  

- name: Display wait time
  debug:
    msg: "This will wait up to {{ wait_time_to_shutdown_or_fail }} minutes before resuming to next tasks"

- name: Probe VM with vish until vm power up
  shell: |
    virsh list --all | sed 's/shut off/shutdown/' | grep -i "^.*{{ vm_host }}.*" | awk '{print $NF}'
  register: vm_state
  vars:
  delegate_to: "{{ kvm_delegate }}"
  failed_when: false
  changed_when: false
  until: (vm_state.stdout | default('')) == "running"
  retries: "{{ build_loops|int }}"
  delay: 10          # 10 seconds between attempts

- name: Wait before after stating
  wait_for:
    timeout: 30
  delegate_to: localhost
  become: false
  when: vm_build_state != "running"

- name: vm_build_state status
  debug:
    msg: "vm_build_state is {{ vm_build_state }}"

- name: Update vm_build_state to running (from polling)
  set_fact:
    vm_build_state: "running"
    vm_build_stage: "booting"
  when: (vm_state_check.stdout | default('')) == "running"

- name: Update vm_build_state to running (already known)
  set_fact:
    vm_build_state: "running"
    vm_build_stage: "booting"
  when: vm_state_check is not defined and vm_build_state == "running"

- name: Wait before SSH check
  wait_for:
    timeout: 30
  delegate_to: localhost
  become: false
  when: vm_build_state == "running"

- name: Probe VM with echo until SSH is ready
  become: false
  shell: echo sshok
  register: ssh_check
  vars:
    ansible_user: "{{ admin_id }}"
    ansible_ssh_pass: "{{ admin_set }}"
    ansible_host: "{{ vm_fqdn }}"
  delegate_to: "{{ vm_host }}"
  failed_when: false
  changed_when: false
  until: (ssh_check.stdout | default('')) == "sshok"
  retries: "{{ build_loops|int }}"
  delay: 10          # 10 seconds between attempts

- name: Show SSH check result
  debug:
    msg: "SSH check result is {{ ssh_check.stdout }}"

- name: Mark VM as ready
  set_fact:
    vm_build_state: "sshok"
    vm_build_stage: "booted"
  when: (ssh_check.stdout | default('')).find('sshok') != -1

- block:
    - name: Dump VM NICs (MAC + bridge) from KVM host
      delegate_to: "{{ kvm_delegate }}"
      become: true
      shell: |
        virsh dumpxml {{ vm_host }} \
          | grep -iE "mac ad|network" \
          | awk '{print $NF}' \
          | tr -d "\n" \
          | sed "s/type='network'>/\n/g" \
          | sed 's/\/>/ /g' \
          | grep bridge
      register: vm_nics_raw

    - name: Parse NIC lines into list
      set_fact:
        vm_nics: "{{ vm_nics_raw.stdout_lines }}"

    - name: Show VM NICs
      debug:
        var: vm_nics

    - name: Gather guest NICs by MAC
      vars:
        ansible_user: "{{ admin_id }}"
        ansible_ssh_pass: "{{ admin_set }}"
        ansible_host: "{{ vm_fqdn }}"
      delegate_to: "{{ vm_host }}"
      become: false
      loop: "{{ vm_nics }}"
      loop_control:
        loop_var: nic
      shell: |
        ip -o link show | grep {{ nic.split()[0].split('=')[1] | trim("'") }} | awk '{print $2}' | sed 's/://'
      register: nic_results

    - name: Build network→device map
      set_fact:
        net_dev_map: "{{ dict(vm_nics | map('regex_replace','.*bridge=\\'(.*?)\\'.*','\\1') | zip(nic_results.results | map(attribute='stdout'))) }}"

    - name: Show network→device map
      debug:
        var: net_dev_map

    - name: Configure cluster NIC
      delegate_to: "{{ vm_host }}"
      vars:
        ansible_user: "{{ admin_id }}"
        ansible_ssh_pass: "{{ admin_set }}"
        ansible_host: "{{ vm_fqdn }}"
      become: true
      shell: >
        nmcli con modify {{ net_dev_map['br-cluster'] }} ipv4.addresses {{ cluster_ip_addr }}/{{ ip_cid }}
        nmcli con modify {{ net_dev_map['br-cluster'] }} ipv4.gateway {{ cluster_gateway }}
        nmcli con modify {{ net_dev_map['br-cluster'] }} ipv4.method manual
        nmcli con modify {{ net_dev_map['br-cluster'] }} ipv4.never-default yes
        nmcli con modify {{ net_dev_map['br-cluster'] }} ipv6.method ignore
        nmcli con modify {{ net_dev_map['br-cluster'] }} connection.autoconnect yes
        nmcli con up {{ net_dev_map['br-cluster'] }}

    - name: Configure NAT NIC
      vars:
        ansible_user: "{{ admin_id }}"
        ansible_ssh_pass: "{{ admin_set }}"
        ansible_host: "{{ vm_fqdn }}"
      delegate_to: "{{ vm_host }}"
      become: true
      shell: >
        nmcli con modify {{ net_dev_map['br-nat'] }} ipv4.method auto
        nmcli con modify {{ net_dev_map['br-nat'] }} ipv4.never-default yes
        nmcli con modify {{ net_dev_map['br-nat'] }} ipv6.method ignore
        nmcli con modify {{ net_dev_map['br-nat'] }} connection.autoconnect yes
        nmcli con up {{ net_dev_map['br-nat'] }}
  when: "'helper_nodes' in group_names or 'cluster_nodes' in group_names"
