# ──────── STAGE: Check existence ─────────
- name: Check if VM exists
  shell: virsh dominfo {{ vm_host }}
  register: vm_check
  failed_when: false
  changed_when: false

- name: Set stage
  set_fact:
    vm_build_stage: >-
      {% if vm_check.rc != 0 %}
        build
      {% elif force_rebuild | default(false) %}
        building
      {% else %}
        present
      {% endif %}

- name: update existing_vms
  set_fact:
    existing_vms: True
  when: vm_build_stage in ['present']

- name: stage status
  debug:
    msg: "stage is {{ vm_build_stage }}"

- name: stage status
  debug:
    msg: "delegate id {{ kvm_delegate }}"

- name: Initialize VM stage map
  set_fact:
    vm_stage_map: "{{ vm_stage_map | default({}) | combine({ vm_host: 'unknown' }) }}"

- name: Set stage to building
  set_fact:
    vm_stage_map: "{{ vm_stage_map | combine({ vm_host: 'building' }) }}"

# ──────── STAGE: Build if needed ─────────
- name: Get current epoch time from localhost
  become: false
  shell: date +%s
  register: epoch_result
  delegate_to: localhost
  # run_once: true
  changed_when: false

- name: Set global epoch fact
  set_fact:
    global_epoch: "{{ epoch_result.stdout | int }}"
  # run_once: true

- name: Set VM shutdown poll start time
  set_fact:
    vm_shutdown_start: "{{ global_epoch }}"

- name: Initialize VM state
  set_fact:
    vm_build_state: "undefined"
    vm_timeout: 0

- name: Trigger build if needed
  include_tasks: define_vms.yml
  when: vm_stage_map[vm_host] in ['build', 'building']


- name: Include shutdown check
  include_tasks: check_vm_state.yml
  when: vm_build_state != "shutdown" and (vm_timeout | int) < shutdown_max_timeout

- name: show status before next check
  debug:
    msg: "vm_build_state {{vm_build_state}}, vm_timeout {{vm_timeout}}"

- name: vm_build_state status befor poll
  debug:
    msg: "vm_build_state is {{ vm_build_state }}"

- name: Poll until VM is shut off or timeout
  include_tasks: nested_loop.yml
  when: 
    - "'kvm' not in group_names"
    - vm_build_state != "running"

- name: vm_build_state status
  debug:
    msg: "vm_build_state is {{ vm_build_state }}"


- name: Fail if VM did not shut off after polling
  fail:
    msg: "VM {{ vm_host }} did not shut off after polling timeout."
  when: vm_build_state != "shutdown" and (vm_timeout | int) > shutdown_max_timeout

