- name: setup ssh keys for main id
  import_tasks: add_keys.yml

- name: Stage Three Provision Groups
  import_tasks: create_groups.yml

- name: Precompute members_map_items
  delegate_to: localhost
  become: false
  set_fact:
    members_map_items: "{{ members_map | dict2items }}"

- name: set up key ids and groups
  import_tasks: key_users.yml

- name: Create users and assign to groups
  loop: "{{ members_map_items }}"
  loop_control:
    loop_var: group_entry
    label: "{{ group_entry.key }} → {{ group_entry.value | join(', ') }}"
  include_tasks: create_users.yml
  vars:
    group_name: "{{ group_entry.key }}"
    members: "{{ group_entry.value }}"

- name: Find user creation scripts
  find:
    paths: /tmp
    patterns: "user_create_script_*.sh"
    file_type: file
  delegate_to: localhost
  become: false
  register: user_scripts

- name: Remove user creation scripts
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ user_scripts.files }}"
  delegate_to: localhost
  become: false

- name: Stage Three Provision Sudoers tmplates
  import_tasks: render_sudoers_templates.yml

- name: Stage four set secure id and is compliance 
  import_tasks: secops_templates.yml

