ipa_domain: "{{ lookup('env', 'ipa_domin`') }}"
dns_zone: "{{ lookup('env', 'dns_zone') }}"
account_name: "{{ lookup('env', 'ACCOUNT') }}"
admin_id: "{{ lookup('env', 'admin_id') }}"
admin_set: "{{ lookup('env', 'admin_set') }}"
# default IDs
secops_id: "secops"
# secops_pw
secops_pw: "{{ lookup('env', 'secops_pwd') }}"
