- name: Run kubeadm init
  command: kubeadm init --config {{ kubeadm_cluster_config_path }} --upload-certs
  register: kubeadm_init_output
  changed_when: true

- name: Show kubeadm init output
  debug:
    var: kubeadm_init_output.stdout_lines
