---
- name: Render Butane templates
  import_tasks: render.yml
  tags:
    - butane rendering
  when: "'helpers' in group_names"

- name: Validate rendered Butane files
  import_tasks: validate.yml
  tags:
    - butane validation

