- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: Restart IPA services
  command: ipactl restart

- name: refresh_repos
  become: true
  command: dnf clean all
  changed_when: false

- name: restart_network
  become: true
  command: nmcli connection reload
  changed_when: false

- name: restart bootstrap api
  systemd:
    name: cloud-helper-bootstrap-api.service
    state: restarted

