- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: "0.2 - Restart FreeIPA Services via ipactl"
  become: true
  shell: "ipactl restart"
  # ipactl returns 0 on success. We use this to ensure Ansible tracks the change.
  register: ipa_restart_result
  changed_when: ipa_restart_result.rc == 0
  # Give it 5 minutes (300s) to restart the entire stack (LDAP, KDC, DNS, CA, UI)
  async: 300
  poll: 5
  tags: [ipa, maintenance]

- name: refresh_repos
  become: true
  command: dnf clean all
  changed_when: false

- name: restart_network
  become: true
  command: nmcli connection reload
  changed_when: false

- name: restart bootstrap api
  systemd:
    name: cloud-helper-bootstrap-api.service
    state: restarted

