- name: Attach new NICs to a powered-off VM
  delegate_to: "{{ kvm_delegate }}"
  become: true
  shell: |
    virsh attach-interface \
      --domain {{ vm_host }} \
      --type network \
      --source {{ item }} \
      --model virtio \
      --config --live
  loop:
    - br-cluster
    - br-nat
  when: vm_state.stdout | default('') == "shutdown"
