- name: Show staus of vm_build_state at stage three start
  debug:
    msg: |
      "vm_build_state is {{ vm_build_state }} at stage three start"
      "vm_build_stage is {{ vm_build_stage }} at stage three start"

- name: setup ssh keys for main id
  import_tasks: add_keys.yml

- name: Stage Three Provision Groups
  import_tasks: create_groups.yml

- name: Precompute members_map_items
  delegate_to: localhost
  become: false
  set_fact:
    members_map_items: "{{ members_map | dict2items }}"

- name: Create users and assign to groups
  loop: "{{ members_map_items }}"
  loop_control:
    loop_var: group_entry
    label: "{{ group_entry.key }} → {{ group_entry.value | join(', ') }}"
  include_tasks: create_users.yml
  vars:
    group_name: "{{ group_entry.key }}"
    members: "{{ group_entry.value }}"

- name: Find user creation scripts
  find:
    paths: /tmp
    patterns: "user_create_script_*.sh"
    file_type: file
  delegate_to: localhost
  become: false
  register: user_scripts

- name: Remove user creation scripts
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ user_scripts.files }}"
  delegate_to: localhost
  become: false

- name: Stage Three Provision Sudoers tmplates
  import_tasks: render_sudoers_templates.yml

- name: Set tmp state
  set_fact:
    vm_tmp_state: "{{ vm_build_state }}"

- name: Stage four set secure id and is compliance 
  import_tasks: secops_templates.yml
  vars:
    vm_build_state: "{{ vm_tmp_state }}"

- name: Show final vm_build_state at stage three end
  debug:
    msg: "vm_build_state is {{ vm_build_state }} at stage three end"

- name: Set global_vm_build_state for next module
  set_fact:
    global_vm_build_state: "configured"
  when: vm_build_state == "non-compliant"

- name: Set global_vm_build_state for next module
  set_fact:
    global_vm_build_state: "ready"
  when: vm_build_state == "compliant"