- name: set ipa password
  set_fact:
    ipa_admin_password: "{{ lookup('env', 'ipa_admin_password')}}"
    ipa_domain: "{{ lookup('env', 'ipa_domain') |lower}}"
    cloud_master: "{{ groups['control_nodes'][0] }}"
    cloud_master_ip: "{{ hostvars[groups['control_nodes'][0]].ansible_host }}"
    cloud_zone: "{{ lookup('env', 'cloud_zone') }}"
    ipa_master: "{{ lookup('env', 'ipa_master') }}"
    ipa_master_ip: "{{ hostvars[groups['dns'][0]].ansible_host }}"
    ipa_second: "{{ groups['dns'][1] }}"
    ipa_second_ip: "{{ hostvars[groups['dns'][1]].ansible_host }}"
    helper_id:  "{{ groups['helpers'][0] }}"
    ingress_id: "{{ lookup('env', 'ingress_id') }}"
    ingress_ip: "{{ lookup('env', 'ingress_ip') }}"

- name: install required code
  import_tasks: install.yml

- name: Common preparation tasks
  become: true
  delegate_to: helper
  import_tasks: prep_cloud.yml
