---
- shell: "sudo /bin/sh -c 'mkdir -p {{ image_path }}/ignition && chmod 755 {{ image_path }}/ignition'"
- copy:
    src: "/tmp/{{ item }}"
    dest: "/tmp/{{ item }}"
  loop: "{{ groups['cluster_nodes'] | reject('equalto', 'helper') | list | map('append', '.ign') | list + [fcos_image_name] }}"
- shell: |
    sudo /bin/sh -c '
    mv /tmp/{{ fcos_image_name }} {{ image_path }}/ ;
    mv /tmp/*.ign {{ image_path }}/ignition/ ;
    chown qemu:qemu {{ image_path }}/ignition/*.ign ;
    restorecon -Rv {{ image_path }}/'
