---
- name: Ensure .ssh directory exists
  file: { path: "~/.ssh", state: directory, mode: '0700' }

- name: Generate SSH Key
  shell: "ssh-keygen -t rsa -b 4096 -f {{ lookup('env', 'HELPER_SSH_KEY_PATH') }} -N ''"
  args:
    creates: "{{ lookup('env', 'HELPER_SSH_KEY_PATH') }}"

- name: Configure SSH client behavior
  blockinfile:
    path: "~/.ssh/config"
    create: yes
    mode: '0600'
    block: |
      Host *
          StrictHostKeyChecking accept-new
          UserKnownHostsFile ~/.ssh/known_hosts
          IdentityFile {{ lookup('env', 'HELPER_SSH_KEY_PATH') }}

- name: Get Public Key
  shell: "cat {{ lookup('env', 'HELPER_SSH_KEY_PATH') }}.pub"
  register: pub_key_out

- set_fact:
    helper_pub_key: "{{ pub_key_out.stdout }}"
