---
- name: Ensure CLOUD_HELPER_USER exists on Helper
  delegate_to: helper
  user:
    name: "{{ cloud_helper_user }}"
    shell: /bin/bash
    groups: podman
    append: yes
    state: present

- name: Pull CoreOS Toolchain Images
  shell: "podman pull quay.io/coreos/{{ item }}:release"
  loop: [butane, coreos-installer, ignition-validate]

- name: Ensure cloud helper work directory exists
  file:
    path: "{{ cloud_helper_workdir }}"
    state: directory
    mode: "0755"

- name: Download FCOS image using podman-based coreos-installer
  shell: |
    alias butane='podman run --rm --interactive \
      --security-opt label=disable \
      --volume "${PWD}:/pwd" --workdir /pwd \
      quay.io/coreos/butane:release'

    alias coreos-installer='podman run --pull=always \
      --rm --interactive \
      --security-opt label=disable \
      --volume "${PWD}:/pwd" --workdir /pwd \
      quay.io/coreos/coreos-installer:release'

    alias ignition-validate='podman run --rm --interactive \
      --security-opt label=disable \
      --volume "${PWD}:/pwd" --workdir /pwd \
      quay.io/coreos/ignition-validate:release'

    coreos-installer download -p qemu -f qcow2.xz --decompress
  args:
    chdir: "{{ cloud_helper_workdir }}"
