
---
- debug: msg="run on {{ helper_node }} curl -I --fail http://{{ nat_ip }}/boot.ipxe"
- name: Test iPXE availability via /boot.ipxe
  delegate_to: "{{ helper_node }}"
  command: >
    curl -I --fail http://{{ nat_ip }}/boot.ipxe
  register: ipxe_test_root
  retries: 5
  delay: 2
  until: ipxe_test_root.rc == 0

- name: Test iPXE availability via /ipxe/boot.ipxe
  delegate_to: "{{ helper_node }}"
  command: >
    curl -I --fail http://{{ nat_ip }}/ipxe/boot.ipxe
  register: ipxe_test_subdir
  retries: 5
  delay: 2
  until: ipxe_test_subdir.rc == 0

- name: Validate iPXE file content matches this VM
  delegate_to: "{{ helper_node }}"
  command: >
    curl -s http://{{ nat_ip }}/boot.ipxe
  register: ipxe_content

- debug: msg="{{ipxe_content}}"
- name: Fail if iPXE file does not match this VM
  fail:
    msg: "boot.ipxe does not contain expected hostname {{ vm }}"
  when: "'{{ vm }}' not in ipxe_content.stdout"
