# prep_role_helper.yml
---
# ---------------------------------------------------------
# Download FCOS live ISO to the KVM host
# ---------------------------------------------------------

- name: Fetch FCOS stable stream metadata
  uri:
    url: "https://builds.coreos.fedoraproject.org/streams/stable.json"
    return_content: yes
  register: fcos_stream_json
  delegate_to: "{{ VM_HOST }}"

# - name: Set FCOS ISO URL (x86_64)
#   set_fact:
#     fcos_iso_url: >-
#       {{ fcos_stream_json.json.architectures.x86_64.artifacts['live-iso'].formats.iso.disk.location }}

- name: Download FCOS live ISO
  get_url:
    url: "{{ fcos_iso_url }}"
    dest: /var/lib/libvirt/boot/fcos-live.iso
    mode: '0644'
  delegate_to: "{{ VM_HOST }}"
