---
# reboot.yml
# Boot into installed FCOS and verify SSH

- name: Start VM after ISO removal
  virt:
    name: "{{ item }}"
    state: running
  loop: "{{ groups['cluster_nodes'] }}"
  delegate_to: "{{ VM_HOST }}"
  tags: [vm_reboot]

- name: Wait for installed FCOS SSH
  wait_for:
    host: "{{ item }}"
    port: 22
    delay: 5
    timeout: 300
  loop: "{{ groups['cluster_nodes'] }}"
  delegate_to: localhost
  tags: [vm_reboot]

- name: Verify FCOS hostname
  ansible.builtin.command: hostnamectl --static
  register: hostname_out
  loop: "{{ groups['cluster_nodes'] }}"
  delegate_to: "{{ item }}"
  tags: [vm_reboot]

- debug:
    msg: "Node {{ item }} hostname: {{ hostname_out.stdout }}"
  loop: "{{ groups['cluster_nodes'] }}"
  tags: [vm_reboot]
