# - name: update_status
#   set_fact:
#     roles_dict: >-
#       {{
#         roles_dict | combine({
#           role_to_read: {
#             'role_name': role_to_read,
#             'tasks': (
#               roles_dict[role_to_read].tasks | map('combine', {
#                 'status': (result is succeeded) | ternary('success','failed'),
#                 'rc': result.rc | default('none')
#               }) | list
#             )
#           }
#         }, recursive=True)
#       }}
#   delegate_to: localhost
#   become: false
