- name: Ensure monitor site directory exists
  delegate_to: localhost
  become: false
  file:
    path: "{{ monitor_target_dir }}"
    state: directory
    mode: '0755'
  register: result

- name: Update status
  include_tasks: "{{role_path}}/tasks/update_status.yml"
  vars:
    role_to_read: "monitors"
    task_name: "Read tasks.json"
    status: "{{ result.stdout }}"
    rc: "{{ parse_output.stderr }}"

- name: Generate private key and self-signed certificate
  command: >
    openssl req -new -x509 -nodes -days 365
    -out {{ monitor_target_dir }}/server.crt
    -keyout {{ monitor_target_dir }}/server.key
    -subj "/CN={{ ansible_fqdn | default(inventory_hostname) }}"
  delegate_to: localhost
  become: false
  args:
    creates: "{{ monitor_target_dir }}/server.crt"
  register: result

- name: update Generate private key
  include_tasks: "{{ role_path }}/tasks/update_status.yml"
  vars:
    role_to_read: monitors
    task_name: "Generate private key and self-signed certificate"
    status: "{{ result.stdout }}"
    rc: "{{ parse_output.stderr }}"

- name: Combine key and cert into PEM bundle
  shell: cat {{ monitor_target_dir }}/server.key {{ monitor_target_dir }}/server.crt > {{ monitor_target_dir }}/server.pem
  delegate_to: localhost
  become: false
  args:
    creates: "{{ monitor_target_dir }}/server.pem"
  register: result

- name: update Generate private key
  include_tasks: "{{ role_path }}/tasks/update_status.yml"
  vars:
    role_to_read: monitors
    task_name: "Combine key and cert into PEM bundle"
    status: "{{ result.stdout }}"
    rc: "{{ parse_output.stderr }}"
  