- name: Ensure monitor site directory exists
  delegate_to: localhost
  become: false
  file:
    path: "{{ monitor_target_dir }}"
    state: directory
    mode: '0755'
  
- name: Generate private key and self-signed certificate
  command: >
    openssl req -new -x509 -nodes -days 365
    -out {{ monitor_target_dir }}/server.crt
    -keyout {{ monitor_target_dir }}/server.key
    -subj "/CN={{ ansible_fqdn | default(inventory_hostname) }}"
  delegate_to: localhost


# - name: Generate private key and self-signed certificate
#   delegate_to: localhost
#   become: false
#   run_once: true
#   shell: |
#     openssl req -new -x509 -nodes -days 365 \
#       -out {{ monitor_target_dir }}/server.crt \
#       -keyout {{ monitor_target_dir }}/server.key
#   # args:
#   #   creates: "{{ monitor_target_dir }}/server.crt"

- name: Combine key and cert into PEM bundle
  delegate_to: localhost
  become: false
  shell: cat {{ monitor_target_dir }}/server.key {{ monitor_target_dir }}/server.crt > {{ monitor_target_dir }}/server.pem
  # args:
  #   creates: "{{ monitor_target_dir }}/server.pem"

