---
# roles/html_monitor/tasks/main.yml
- name: get work dir
  set_fact: 
    workDir: "{{ playbook_dir | dirname }}"

- name: set file list
  set_fact: 
    playlist: []
  delegate_to: localhost

- name: files read order
  import_tasks: read_includes.yml

- block:
    - import_tasks: site_mon.yml
    - import_tasks: start_mon.yml
    # - import_tasks: certs.yml
    # - import_tasks: readplaybook.yml
  delegate_to: localhost


# ADD this to end of playbook if your not running httpd service
# - name: get work dir
#   set_fact: 
#     workDir: "{{ playbook_dir | dirname }}"
#
# - name: Stop Python HTTPS server
#   ansible.builtin.shell: |
#     if [ -f {{ monitor_target_dir }}/server.pid ]; then
#       kill $(cat {{ monitor_target_dir }}/server.pid) && rm -f {{ monitor_target_dir }}/server.pid
#     fi
#   delegate_to: localhost
#   become: false
