---
# roles/html_monitor/tasks/main.yml
- name: set file list
  set_fact: 
    playlist: []
  delegate_to: localhost

- name: Update status for command (no register → defaults to complete)
  include_tasks: roles/monitors/tasks/update_status.yml
  vars:
    role_to_read: "monitors"
    task_name: "set file list"

- name: files read order
  import_tasks: read_includes.yml

- block:
    - import_tasks: site_mon.yml
    - import_tasks: certs.yml
    # - import_tasks: readplaybook.yml
  delegate_to: localhost
