- name: get work dir
  set_fact: 
    workDir: "{{ playbook_dir | dirname }}"

- name: Run playbook parser
  ansible.builtin.command:
    cmd: >
      python3 {{ role_path }}/scripts/build_json_list.py
      -d {{ workDir }}
      -p playbooks/{{ playbook_name }}
      -i {{ workDir }}/inventory.yml
      -r {{ workDir }}/roles
    chdir: "{{ workDir }}"
  register: parse_output
  delegate_to: localhost
  run_once: yes
  become: false

- name: Update status
  include_tasks: "{{role_path}}/update_status.yml"
  vars:
    role_to_read: "monitors"
    task_name: "Run playbook parser"
    result: "{{ parse_output }}"
    rc: "{{ parse_output.stderr }}"

- name: Read tasks.json
  ansible.builtin.slurp:
    src: "{{ workDir }}/buildMon/tasks.json"
  register: tasks_file
  delegate_to: localhost
  run_once: yes
  become: false

- name: Update status
  include_tasks: update_status.yml
  vars:
    role_to_read: "monitors"
    task_name: "Read tasks.json"
    status: "complete"
    rc: ""

- name: Parse tasks.json
  set_fact:
    tasks_data: "{{ tasks_file.content | b64decode | from_json }}"

- name: Update status
  include_tasks: update_status.yml
  vars:
    role_to_read: "monitors"
    task_name: "Read tasks.json"
    status: "complete"
    rc: ""

- name: Show ordered task list
  debug:
    var: tasks_data

