# roles/monitors/tasks/update_status.yml
- name: Update roles_dict for {{ task_name }}
  set_fact:
    roles_dict: >-
      {{
        (roles_dict | default({})) | combine({
          role_to_read: {
            'role_name': role_to_read,
            'tasks': (
              (roles_dict[role_to_read].tasks | default([]))
              + [
                {
                  'name': task_name,
                  'status': status | default(
                    result is defined
                    | ternary(
                        (result.rc|default(1)) == 0 | ternary('success','failed'),
                        'complete'
                      )
                  ),
                  'rc': result.rc | default('none'),
                  'error': serror | default('')
                }
              ]
            )
          }
        }, recursive=True)
      }}
  delegate_to: localhost
  run_once: true
  become: false

- name: Update tasks.json for {{ task_name }}
  command: >
    jq '(.plays[].tasks[] | select(.name=="{{ task_name }}" and .role=="{{ role_to_read }}"))
        |= . + {status:"{{ status | default("pending") }}", error:"{{ serror | default("") }}"}'
    {{ workDir }}/buildMon/tasks.json
  register: updated_json
  delegate_to: localhost
  run_once: true
  become: false

- name: Save updated tasks.json
  copy:
    dest: "{{ workDir }}/buildMon/tasks.json"
    content: "{{ updated_json.stdout }}"
    mode: '0644'
  delegate_to: localhost
  run_once: true
  become: false

