- name: Update tasks.json for multiple tasks
  command: >
    sh -c 'jq ".plays[].tasks |= map(
      if .name == \"{{ task_finish }}\" then
        .tags |= (
          if (.tags|length)==0 then
            [{\"status\":\"{{ tast_status }}\",\"rc\":\"{{ rc | default("") }}\"}]
          else
            map(
              if has(\"status\") then .status=\"{{ tast_status }}\" | .rc=\"{{ rc | default("") }}\" | .
              else . end
            )
          end
        )
      elif .name == \"{{ task_start }}\" then
        .tags |= (
          if (.tags|length)==0 then
            [{\"status\":\"starting\",\"rc\":\"\"}]
          else
            map(if has(\"status\") then .status=\"starting\" | . else . end)
          end
        )
      else . end
    )" {{ workDir }}/buildMon/tasks.json > {{ workDir }}/buildMon/tasks.tmp && mv {{ workDir }}/buildMon/tasks.tmp {{ workDir }}/buildMon/tasks.json'
  delegate_to: localhost
  run_once: true
  become: false
  when: task_finish is defined

- name: Update tasks.json for {{ task_name }}
  command: >
    sh -c 'jq "(.plays[].tasks[]
             | select(.name==\"{{ task_name }}\" and .role==\"{{ role_to_read }}\"))
           |= (.tags |=
                (if (.tags|length)==0
                 then [{\"status\":\"{{ tast_status }}\",\"rc\":\"{{ rc | default("") }}\"}]
                 else map(
                   if has(\"status\") then .status=\"{{ tast_status }}\" | .rc=\"{{ rc | default("") }}\" | .
                   else . end
                 )
                 end))" {{ workDir }}/buildMon/tasks.json > {{ workDir }}/buildMon/tasks.tmp && mv {{ workDir }}/buildMon/tasks.tmp {{ workDir }}/buildMon/tasks.json'
  delegate_to: localhost
  run_once: true
  become: false
  when: task_finish is not defined

- name: Mark task as failed in tasks.json
  command: >
    sh -c 'jq "(.plays[].tasks[]
             | select(.name==\"{{ task_name }}\" and .role==\"{{ role_to_read }}\"))
           |= (.tags |=
                (if (.tags|length)==0
                 then [{\"status\":\"failed\",\"rc\":\"{{ rc | default("1") }}\"}]
                 else map(
                   if has(\"status\") then .status=\"failed\" | .rc=\"{{ rc | default("1") }}\" | .
                   else . end
                 )
                 end))" {{ workDir }}/buildMon/tasks.json > {{ workDir }}/buildMon/tasks.tmp && mv {{ workDir }}/buildMon/tasks.tmp {{ workDir }}/buildMon/tasks.json'
  delegate_to: localhost
  run_once: true
  become: false
  when: rc is defined and rc|int != 0
