# - name: Ensure Apache is listing on port 80
#   copy:
#     content: |
#       Listen 80
#     dest: /etc/httpd/conf.d/listen-ports.conf
#     mode: '0644'

- name: Deploy Apache repo config
  template:
    src: rocky-repo.conf.j2
    dest: /etc/httpd/conf.d/rocky-repo.conf
    mode: '0644'
  vars:
    rocky_version: "{{ rocky_major }}"


- name: Allow httpd to read mounted content
  seboolean:
    name: httpd_read_user_content
    state: true
    persistent: true

- name: Ensure Apache is started and enabled manually
  shell: |
    systemctl enable httpd
    systemctl start httpd

- name: Allow HTTP temporarily
  ansible.posix.firewalld:
    service: http
    state: enabled
    immediate: yes
    permanent: no

- name: Allow HTTPS temporarily
  ansible.posix.firewalld:
    service: https
    state: enabled
    immediate: yes
    permanent: no
