---
- name: 1.1 - Verify Unique Identity
  assert:
    that:
      - ansible_machine_id != hostvars[groups['control_nodes'][1]]['ansible_machine_id']
    fail_msg: "CRITICAL: Nodes share the same machine-id! Sysprep failed."
  when: inventory_hostname == groups['control_nodes'][0]

- name: 1.2 - Ensure CRI-O is started and enabled
  systemd:
    name: crio
    state: started
    enabled: yes

- name: 1.3 - Check Container Runtime Health
  command: crictl info
  register: crio_check
  changed_when: false

- name: 1.4 - Ensure Kubelet is enabled but stopped
  systemd:
    name: kubelet
    enabled: yes
    state: stopped