---
- name: 1.1 - Verify Unique Identity
  assert:
    that:
      - ansible_machine_id != hostvars[groups['control_nodes'][1]]['ansible_machine_id']
    fail_msg: "CRITICAL: Nodes share the same machine-id! Sysprep failed."
  when: inventory_hostname == groups['control_nodes'][0]

- name: 1.2 - Ensure CRI-O is started and enabled
  systemd:
    name: crio
    state: started
    enabled: yes

- name: 1.3 - Check Container Runtime Health
  command: crictl info
  register: crio_check
  changed_when: false

- name: 1.4 - Ensure Kubelet is enabled but stopped
  systemd:
    name: kubelet
    enabled: yes
    state: stopped

- name: 1.5 - Load Required Kernel Modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: 1.6 - Persist Kernel Modules on Boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: 1.7 - Set Sysctl Parameters for K8s
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  loop:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { key: 'net.ipv4.ip_forward', value: '1' }