# 1. Fetch the config
- name: 4.1 - Fetch admin.conf to local kubeconfig
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ lookup('env', 'USER') }}/.kube/config"
    flat: yes
  when: inventory_hostname == groups['control_nodes'][0]

# 2. Fix permissions locally
- name: 4.2 - Fix local kubeconfig permissions
  delegate_to: localhost
  run_once: true
  file:
    path: "/home/{{ lookup('env', 'USER') }}/.kube/config"
    owner: "{{ lookup('env', 'USER') }}"
    mode: '0600'
    state: file

# # 3. Interactive Pause for Manual Intervention
# - name: 4.3 - MANUAL STEP REQUIRED
#   pause:
#     prompt: |
#       -------------------------------------------------------------------------
#       KUBERNETES API IS INITIALIZING. 
      
#       Please open a NEW terminal on your helper node and run:
#       kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      
#       Once you see 'daemonset.apps/kube-flannel-ds created',
#       run kubectl get nodes to see if ready, 
#       press ENTER here to continue the playbook.
#       -------------------------------------------------------------------------
#   run_once: true

# 3. Interactive Pause for Manual Intervention
- name: 4.3 - MANUAL STEP REQUIRED
  pause:
    prompt: |
      -------------------------------------------------------------------------
      KUBERNETES API IS INITIALIZING. 
      
      Please open a NEW terminal on your helper node and run:
      kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      
      Once you see 'daemonset.apps/kube-flannel-ds created',
      run kubectl get nodes to see if ready, 
      press ENTER here to continue the playbook.
      -------------------------------------------------------------------------
  run_once: true
  environment:
    KUBECONFIG: "/home/{{ lookup('env', 'USER') }}/.kube/config"

# . Automated Wait for 'Ready' Status
- name: 4.6 - Wait for all 5 nodes to transition to Ready
  shell: "kubectl get nodes | grep ' Ready ' | wc -l"
  delegate_to: localhost
  register: ready_count
  # We expect 5 (msrlv9mast01-03 + msrlv9wrk01-02)
  until: ready_count.stdout | trim | int == 5
  retries: 30
  delay: 10
  run_once: true
  environment:
    KUBECONFIG: "/home/{{ lookup('env', 'USER') }}/.kube/config"