- name: 6.1 - Install MetalLB Manifests
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml
  delegate_to: localhost
  run_once: true
  environment:
    KUBECONFIG: "/home/{{ lookup('env', 'USER') }}/.kube/config"

- name: 6.2 - Wait for MetalLB Controller to be Ready
  shell: "kubectl get deployment controller -n metallb-system -o jsonpath='{.status.readyReplicas}'"
  delegate_to: localhost
  register: metallb_ready
  until: metallb_ready.stdout | trim | int >= 1
  retries: 20
  delay: 10
  run_once: true
  environment:
    KUBECONFIG: "/home/{{ lookup('env', 'USER') }}/.kube/config"