- name: 6.1.0 - Check if Ingress Controller Namespace exists
  delegate_to: localhost
  run_once: true
  environment:
    KUBECONFIG: "/home/{{ ansible_user_id }}/.kube/config"
  ansible.builtin.shell: |
    kubectl get namespace ingress-nginx --no-headers
  register: ingress_ns_check
  failed_when: false
  changed_when: false

- name: 6.1.1 - Deploy NGINX Ingress Controller
  shell: |
    kubectl apply --validate=false -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/baremetal/deploy.yaml
  environment:
    KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"
  register: ingress_result
  until: ingress_result.rc == 0
  retries: 5
  delay: 20

- name: 6.1.2 - Wait for Ingress Controller Pods (Only if we just deployed)
  delegate_to: localhost
  run_once: true
  environment:
    KUBECONFIG: "/home/{{ ansible_user_id }}/.kube/config"
  ansible.builtin.shell: |
    kubectl wait --namespace ingress-nginx \
      --for=condition=ready pod \
      --selector=app.kubernetes.io/component=controller \
      --timeout=120s
  # Only wait if we actually performed a deployment or if the check failed
  when: ingress_ns_check.rc != 0 or (ingress_deploy is defined and ingress_deploy.changed)

- name: 6.1.3 - Always Discover NodePorts (Needed for HAProxy template)
  delegate_to: localhost
  run_once: true
  environment:
    KUBECONFIG: "/home/{{ ansible_user_id }}/.kube/config"
  ansible.builtin.shell: |
    kubectl get svc ingress-nginx-controller -n ingress-nginx \
    -o jsonpath='{.spec.ports[?(@.name=="http")].nodePort} {.spec.ports[?(@.name=="https")].nodePort}'
  register: discovered_nodeports

- name: 6.1.4 - Set Facts for the Bridge
  ansible.builtin.set_fact:
    ingress_http_nodeport: "{{ discovered_nodeports.stdout.split()[0] | trim }}"
    ingress_https_nodeport: "{{ discovered_nodeports.stdout.split()[1] | trim }}"