- name: 6.1.0 - Check if Ingress Controller Namespace exists
  delegate_to: localhost
  run_once: true
  environment:
    KUBECONFIG: "/home/{{ ansible_user_id }}/.kube/config"
  ansible.builtin.shell: |
    kubectl get namespace ingress-nginx --no-headers
  register: ingress_ns_check
  failed_when: false
  changed_when: false

- name: Setup kubeconfig for core user
  become: yes
  block:
    - name: Create .kube directory
      shell: |
        mkdir -p /home/core/.kube
        chown core:core /home/core/.kube
        chmod 750 /home/core/.kube

    - name: Copy admin.conf to user home
      shell: |
        sudo cp -f /etc/kubernetes/admin.conf /home/core/.kube/config
        sudo chown core:core /home/core/.kube/config
        sudo chmod 600 /home/core/.kube/config  

  when: "'control_nodes' in group_names"

- name: 6.1.1 - Deploy NGINX Ingress Controller
  shell: |
    kubectl apply --kubeconfig=/etc/kubernetes/admin.conf --validate=false -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/baremetal/deploy.yaml
  # Run this only once from the master node that has the config
  run_once: true
  delegate_to: msrlv9mast01
  become: false
  environment:
    # Use the absolute path to the config on that node
    KUBECONFIG: "/home/{{ ansible_user_id }}/.kube/config" 
  register: ingress_result
  until: ingress_result.rc == 0
  retries: 5
  delay: 15

- name: 6.1.2 - Wait for Ingress Controller Pods (Only if we just deployed)
  delegate_to: localhost
  run_once: true
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user_id }}/.kube/config"
  ansible.builtin.shell: |
    kubectl wait --kubeconfig=/home/{{ ansible_user_id }}/.kube/config --namespace ingress-nginx \
      --for=condition=ready pod \
      --selector=app.kubernetes.io/component=controller \
      --timeout=180s
  # Only wait if we actually performed a deployment or if the check failed
  when: ingress_ns_check.rc != 0 or (ingress_deploy is defined and ingress_deploy.changed)

- name: 6.1.3 - Always Discover NodePorts (Needed for HAProxy template)
  delegate_to: localhost
  run_once: true
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user_id }}/.kube/config"
  ansible.builtin.shell: |
    kubectl get svc ingress-nginx-controller -n ingress-nginx \
    -o jsonpath='{.spec.ports[?(@.name=="http")].nodePort} {.spec.ports[?(@.name=="https")].nodePort}'
  register: discovered_nodeports

- name: 6.1.4 - Set Facts for the Bridge
  ansible.builtin.set_fact:
    ingress_http_nodeport: "{{ discovered_nodeports.stdout.split()[0] | trim }}"
    ingress_https_nodeport: "{{ discovered_nodeports.stdout.split()[1] | trim }}"