---
# 1. Run verification on ALL nodes first
- import_tasks: 01_k8s_verify.yml

# 2. Run Initialize ONLY on the first master
- import_tasks: 02_k8s_initialize.yml

# 3. Run Join on everything else
- import_tasks: 03_k8s_join.yml

# 4. run post init
- import_tasks: 04_post_init.yml
- import_tasks: 04b_fix_firewall.yml

- name: Setup Dashboard Infrastructure
  ansible.builtin.import_tasks: dashboard.yml
  when: inventory_hostname in groups['masters'][0]

- name: Verify Dashboard and Get Token
  ansible.builtin.import_tasks: verify_dashboard.yml
  when: inventory_hostname in groups['masters'][0]

# 5. test it
- import_tasks: 05_smoke_test.yml

# # 6. Pre-check MetalLB IP range
# - import_tasks: 06_metallb.yml



- name: Pre-check MetalLB IP against HAProxy VIP
  fail:
    msg: "STOP! MetalLB range overlaps with the Control Plane VIP (.30). Change metallb-config.yaml!"
  when: "'192.168.100.30' in lookup('file', 'metallb-config.yaml')"