- name: Push to staging area on {{ item }}
  ansible.builtin.copy:
    src: "/tmp/haproxy.cfg.generated"
    dest: "/tmp/haproxy.cfg.tmp"
    mode: '0644'
  delegate_to: "{{ item }}"

- name: Move staging to live config on {{ item }}
  ansible.builtin.command: "sudo mv /tmp/haproxy.cfg.tmp /etc/haproxy/haproxy.cfg"
  delegate_to: "{{ item }}"
  
- name: Move staging to live config on {{ item }}
  ansible.builtin.command: "sudo chmod 644 /etc/haproxy/haproxy.cfg && sudo chown root:root /etc/haproxy/haproxy.cfg"
  delegate_to: "{{ item }}"
  
- name: Move staging to live config on {{ item }}
  ansible.builtin.command: "sudo systemctl restart haproxy"
  delegate_to: "{{ item }}"
