ipa_dns_zone: "cloud.home.morinsoft.ca"
ipa_admin_user: "admin"
ipa_admin_password: "{{ lookup('env', 'ipa_admin_password=') }}"

ipa_api_record: "api"
ipa_apps_record: "*.apps"
ipa_register_workers: false
