---
# # Install coreos-installer on helper (optional)

# - name: Try distro package install coreos-installer
#   package:
#     name: coreos-installer
#     state: present
#   register: coreos_pkg
#   failed_when: false
#   when: install_coreos_installer_on_helper

# - name: Download coreos-installer binary if package not available
#   get_url:
#     url: "https://github.com/coreos/coreos-installer/releases/latest/download/coreos-installer-x86_64"
#     dest: /usr/local/bin/coreos-installer
#     mode: "0755"
#   when:
#     - install_coreos_installer_on_helper
#     - (coreos_pkg is failed) or (coreos_pkg is defined and coreos_pkg.changed is not defined and coreos_pkg.rc is defined and coreos_pkg.rc != 0)
