---
- name: who am I
  command: whoami
  become: false
  register: whoami_out
- debug:
    msg: "Current user is {{ whoami_out.stdout }}"

# Orchestrator: include focused task files in order
- import_tasks: users.yml
- import_tasks: preflight.yml
  vars:
    ansible_user: "{{ admin_id }}"
    ansible_ssh_pass: "{{ admin_set }}"

- import_tasks: helper_space.yml
- import_tasks: keys.yml
- import_tasks: https_certs.yml
# - import_tasks: nginx.yml
- import_tasks: repo.yml
- import_tasks: packages.yml
- import_tasks: podman.yml
- import_tasks: kubernetes.yml
- import_tasks: add_zone.yml
- import_tasks: configure_nginx.yml
- import_tasks: boot_strap.yml
- import_tasks: ignition.yml
# ============================================================
# rocky-only block
# ============================================================
- name: Gather facts manually
  become: false
  setup:

- debug:
    msg: "OS Family: {{ ansible_facts['os_family'] }}, Distribution: {{ ansible_facts['distribution'] }}"

- name: FCOS-only containerd setup
  block:
    # - name: Include rpm-ostree layering
    #   import_tasks: ostree.yml
    - name: Include CRI setup
      import_tasks: containerd.yml
      when: fcos_cri == "containerd"
    - name: Include kubelet setup
      import_tasks: kubelet.yml
  when: >
    ansible_facts['os_family'] == "RedHat"
    and ansible_facts['distribution'] == "Rocky"

- name: add sudoers entry for cloud_helper user
  import_tasks: render_sudoers_templates.yml
  when: inventory_hostname == helper_node

# - name: Build nodes
#   import_tasks: nodes.yml

# - name: restart bootstrap api
#   systemd:
#     name: cloud-helper-bootstrap-api.service
    # state: stopped

- name: Show summary
  debug:
    msg:
      - "cloud_helper user created on helper and KVM host (if requested)."
      - "Public key installed on KVM host for SSH access."
      - "Wrapper script installed at {{ helper_bin_dir }}/{{ virsh_wrapper_name }} (run as cloud_helper)."
      - "To use: export KVM_HOST=<kvm_host> ; {{ helper_bin_dir }}/{{ virsh_wrapper_name }} list --all"
