###############################################
# Helper Node Identity & Paths
###############################################
cloud_helper_user: "{{ lookup('env','CLOUD_HELPER_USER') | default('cloud_helper', true) }}"
cloud_helper_workdir: "{{ lookup('env','HELPER_WORKDIR') | default('/opt/' ~ cloud_helper_user, true) }}"
cloud_helper_bin_dir: "{{ lookup('env','HELPER_BIN_DIR') | default(cloud_helper_workdir ~ '/bin', true) }}"
cloud_helper_venv_path: "{{ lookup('env','CLOUD_HELPER_VENV') | default('/opt/cloud_helper/venv', true) }}"
cloud_helper_ssh_key: "{{ lookup('env','HELPER_SSH_KEY_PATH') | default(cloud_helper_workdir ~ '/id_rsa_cloud_helper', true) }}"
cloud_helper_ssh_pubkey: "{{ lookup('env','helper_ssh_pubkey_path') | default(cloud_helper_ssh_key ~ '.pub', true) }}"
nat_ip_device: "{{ lookup('env','nat_ip_device') | default('172.16.0.20', true) }}"
fcos_iso_url: "{{ lookup('env','FCOS_ISO_URL') | default('https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/43.20251120.3.0/x86_64/fedora-coreos-43.20251120.3.0-live-iso.x86_64.iso', true) }}"
fcos_iso_sig: "{{ lookup('env','FCOS_ISO_SIG') | default('https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/43.20251120.3.0/x86_64/fedora-coreos-43.20251120.3.0-live-iso.x86_64.iso.sig', true) }}"
fcos_iso_sha256: "{{ lookup('env','FCOS_ISO_SHA256') | default('5529503bfed563171d599b5df6a8588a23ac963149e4ac3d185acf7cd51aa3d1', true) }}"