---

- name: Ensure ssh-users group exists
  delegate_to: helper
  group:
    name: ssh-users
    state: present

- name: Ensure {{cloud_id}} user exists on helper
  delegate_to: helper
  user:
    name: "{{cloud_id}}"
    shell: /bin/bash
    create_home: yes
    groups: ""          # explicitly no groups
    append: no

- name: Lock "{{cloud_id}}" password (no password login)
  delegate_to: helper
  command: passwd -l "{{cloud_id}}"
