# main/yml
---

- block:
    # map nics
    - include_tasks: map_nics.yml
    - set_fact:
        vm_nat_ip_map: "{{vm_nic_map}}"
    # Prepare helper automation user + keypair
    - include_tasks: helper_user.yml
    - include_tasks: helper_key.yml

    # After VMs boot: generate per-VM keys and distribute
    - include_tasks: vm_generate_keys.yml
    - include_tasks: vm_collect_keys.yml
    - include_tasks: vm_distribute_keys.yml

  when:
    - role_action is defined
    - "'firstboot' in role_action"
