---
# STEP 1 — GET NIC LISTS FOR EACH VM
- name: Get NIC list for VM
  delegate_to: "{{ VM_HOST }}"
  shell: |
    virsh domiflist {{ item }} | awk 'NR>2 {print $5, $3}'
  register: vm_nics
  loop: "{{ node_list }}"
  loop_control:
    loop_var: item

- debug: 
    msg: |
      - "virsh domiflist {{ item }} | awk 'NR>2 {print $5, $3}'"
      - "vm_nics {{ vm_nics }}"
  loop: "{{ node_list }}"
  loop_control:
    loop_var: item


# STEP 1.5 — SAFELY PARSE NICs
- name: Build vm_nic_map
  set_fact:
    vm_nic_map: "{{ vm_nic_map | default({}) | combine({ item: {
        'nat_mac':     nat_mac,
        'cluster_mac': cluster_mac,
        'provider_mac': provider_mac
    }}) }}"
  vars:
    nic_lines: "{{ vm_nics.results[idx].stdout_lines | default([]) }}"
    nat_mac: >-
      {{ (nic_lines | select('search','br-nat') | list | first | default('ERROR no br-nat')) .split()[0] }}
    cluster_mac: >-
      {{ (nic_lines | select('search','br-cluster') | list | first | default('ERROR no br-cluster')) .split()[0] }}
    provider_mac: >-
      {{ (nic_lines | select('search','default') | list | first | default('ERROR no default')) .split()[0] }}
  loop: "{{ node_list }}"
  loop_control:
    loop_var: item
    index_var: idx
