---

- name: Distribute VM public keys to all nodes
  delegate_to: helper
  become: yes
  become_user: "{{cloud_id}}"
  shell: |
    ssh -i ~/.ssh/cluster_automation \
        -o StrictHostKeyChecking=no \
        core@{{ vm_nat_ip_map[target] }} \
        "echo '{{ vm_pubkey_map[src] }}' >> ~/.ssh/authorized_keys"
  vars:
    target: "{{ item.0 }}"
    src: "{{ item.1 }}"
  loop: "{{ node_list | product(node_list) }}"
  loop_control:
    loop_var: item
