---
- name: Generate per-VM SSH keypair for core on helper
  delegate_to: helper
  become: yes
  become_user: "{{cloud_id}}"
  shell: |
    ssh -i ~/.ssh/cluster_automation \
        -o StrictHostKeyChecking=no \
        core@{{ helper_nat_ip }} \
        "test -f ~/.ssh/id_ed25519 || ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ''"
  loop: "{{ node_list }}"
  loop_control:
    loop_var: item
