---
- name: load environment
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure latest stable collections are installed on controller
      delegate_to: localhost
      become: false
      run_once: true
      command: "ansible-galaxy collection install {{ item }} --upgrade"
      loop:
        - community.general
        - ansible.posix
        - kubernetes.core  # Highly recommended for your FCOS/K8s work
      changed_when: false # These commands check for updates every time

    - name: load environment
      set_fact:
        VM_HOST: "{{ lookup('env','VM_HOST')}}"
        secops_id: "{{ lookup('env', 'secops_id') }}"
        cloud_id: "{{ lookup('env', 'cloud_id') }}"
        secops_pwd: "{{ lookup('env', 'secops_pwd') }}"
        kubetnet_version: "{{ lookup('env', 'kubetnet_version') }}"
        cluster_ip_addr: "{{ lookup('env', 'cluster_ip_addr') }}"
        cluster_netmask: "{{ lookup('env', 'cluster_netmask') }}"
        cloud_zone: "{{ lookup('env', 'cloud_zone') }}"
        cluster_gateway: "{{ lookup('env', 'cluster_gateway') }}"
        default_netmask: "{{ lookup('env', 'default_netmask') }}"
        default_net_device: "{{ lookup('env', 'default_net_device') }}"
        cluster_net_device: "{{ lookup('env', 'cluster_net_device') }}"
        nat_net_device: "{{ lookup('env', 'nat_net_device') }}"
        default_ansible_pwd: "{{ lookup('env', 'secops_pwd') }}"
        secops_key: "{{ lookup('env','secops_key') }}"
        secops_edkey: "{{ lookup('env','secops_edkey') }}"
        ssh_key_path: "{{ lookup('env', 'ssh_key_path')| to_json }}"
        account_name: "{{ lookup('env', 'account_name') }}"
        masters: "{{ groups['control_nodes'] | default([]) }}"
        workers: "{{ groups['worker_nodes'] | default([]) }}"
        helper_node: "{{ groups['helpers'][0] | default([]) }}"
        helper_node_ip: "{{ hostvars[groups['helpers'][0]].ansible_host }}"
        node_list: "{{ groups['control_nodes'] + groups['worker_nodes'] }}"

        # Network layout
        cloud_networks:
          house: "192.168.100.0/24"
          private: "10.0.0.0/24"
          nat: "172.16.0.0/24"

        # Interface mapping
        cloud_interfaces:
          house: "enp1s0"
          private: "enp2s0"
          nat: "enp3s0"
        
# # Stage 1 prep helper to be able to deploy nodes
# - name: Configure cloud helper and minimal KVM host changes
#   hosts: helper
#   become: true
#   roles:
#     - role: cloud-helper

- hosts: helper
  become: true
  gather_facts: false
  roles:
    - cloud_bootstrap

- hosts: control_nodes
  gather_facts: false
  roles:
    - k8s_bootstrap

- hosts: worker_nodes
  gather_facts: false
  roles:
    - k8s_bootstrap

- name: Validate cluster nodes
  gather_facts: false
  hosts: control_nodes
  become: true
  tasks:
    - name: Get node list
      command: kubectl get nodes -o wide
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: nodes

    - debug:
        var: nodes.stdout
