
- name: load environment
  hosts: all
  gather_facts: false
  tasks:
    
    - name: load environment
      set_fact:
        VM_HOST: "{{ lookup('env','VM_HOST')}}"
        ipa_domain: "{{ lookup('env', 'ipa_domain') }}"
        ipa_admin_password: "{{ lookup('env', 'ipa_admin_password') }}"
        dns_zone: "{{ lookup('env', 'dns_zone') }}"
        admin_id: "{{ lookup('env', 'admin_id') }}"
        admin_set: "{{ lookup('env', 'admin_set') }}"
        secops_id: "{{ lookup('env', 'secops_id') }}"
        cloud_id: "{{ lookup('env', 'cloud_id') }}"
        secops_pwd: "{{ lookup('env', 'secops_pwd') }}"
        kubetnet_version: "{{ lookup('env', 'kubetnet_version') }}"
        cluster_ip_addr: "{{ lookup('env', 'cluster_ip_addr') }}"
        cluster_netmask: "{{ lookup('env', 'cluster_netmask') }}"
        cloud_zone: "{{ lookup('env', 'cloud_zone') }}"
        cluster_gateway: "{{ lookup('env', 'cluster_gateway') }}"
        default_netmask: "{{ lookup('env', 'default_netmask') }}"
        default_net_device: "{{ lookup('env', 'default_net_device') }}"
        cluster_net_device: "{{ lookup('env', 'cluster_net_device') }}"
        nat_net_device: "{{ lookup('env', 'nat_net_device') }}"
        default_ansible_pwd: "{{ lookup('env', 'secops_pwd') }}"
        secops_key: "{{ lookup('env','secops_key') }}"
        secops_edkey: "{{ lookup('env','secops_edkey') }}"
        ssh_key_path: "{{ lookup('env', 'ssh_key_path')| to_json }}"
        account_name: "{{ lookup('env', 'account_name') }}"
        masters: "{{ groups['control_nodes'] | default([]) }}"
        workers: "{{ groups['worker_nodes'] | default([]) }}"
        helper_node: "{{ groups['helpers'][0] | default([]) }}"
        helper_node_ip: "{{ hostvars[groups['helpers'][0]].ansible_host }}"
        node_list: "{{ groups['control_nodes'] + groups['worker_nodes'] }}"

        # Network layout
        cloud_networks:
          house: "192.168.100.0/24"
          private: "10.0.0.0/24"
          nat: "172.16.0.0/24"

        # Interface mapping
        cloud_interfaces:
          house: "enp1s0"
          private: "enp2s0"
          nat: "enp3s0"

    - debug:
        msg: "var helper_node is {{ helper_node }} with IP {{ helper_node_ip }}"  

    - name: who am I
      vars:
        ansible_user: "{{ secops_id }}"
        ansible_ssh_pass: "{{ secops_pwd }}"
        # ansible_host: "{{ vm_fqdn }}"
      command: whoami
      become: false
      register: whoami_out
      # delegate_to: localhost
    - debug:
        msg: "Current user is {{ whoami_out.stdout }}"


    - name: Gather helper NAT IP (JSON safe)
      vars:
        ansible_user: "{{ admin_id }}"
        ansible_ssh_pass: "{{ admin_set }}"
        # ansible_host: "{{ vm_fqdn }}"
      command: /usr/sbin/ip -4 -o addr show scope global
      register: ip_output
      delegate_to: "{{ helper_node }}"
      when: inventory_hostname == helper_node
      become: false

    - name: Extract 172.x.x.x IP
      set_fact:
        helper_nat_ip: "{{ ip_output.stdout_lines | map('regex_search', '172\\.\\d+\\.\\d+\\.\\d+') | select('string') | list | first }}"
      when: inventory_hostname == helper_node

    
    - set_fact:
        fcos_cloud_support_pub_key: ""
        vm_nat_ip_map: null


- name: fix helpers status for cloud deployments
  gather_facts: false
  hosts: helper
  become: true
  roles:
    - cloud-helper
    