- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: Restart IPA services
  command: ipactl restart
