---
- name: Add API endpoint
  become: yes
  command: >
    ipa dnsrecord-add {{ ipa_dns_zone }} {{ ipa_api_record }}
    --a-ip-address={{ hostvars[masters[0]].ansible_host }}
  register: api_dns
  failed_when: >
    api_dns.rc != 0
    and ('already exists' not in api_dns.stderr)
    and ('no modifications' not in api_dns.stderr)
  changed_when: "'Added record' in api_dns.stdout"

- name: Add apps wildcard endpoint
  command: >
    ipa dnsrecord-add {{ ipa_dns_zone }} "{{ ipa_apps_record }}"
    --a-ip-address={{ hostvars[masters[0]].ansible_host }}
  register: apps_dns
  failed_when: >
    apps_dns.rc != 0
    and ('already exists' not in apps_dns.stderr)
    and ('no modifications' not in apps_dns.stderr)
  changed_when: "'Added record' in apps_dns.stdout"
