---
- name: Add A records for workers (optional)
  when: ipa_register_workers
  command: >
    ipa dnsrecord-add {{ ipa_dns_zone }} {{ hostvars[item].hostname }}
    --a-ip-address={{ hostvars[item].ansible_host }}
  loop: "{{ workers }}"
  register: worker_dns
  failed_when: worker_dns.rc not in [0, 2]
  changed_when: worker_dns.rc == 0
