---
- name: Register Golden Base in FreeIPA DNS
  delegate_to: localhost
  run_once: true
  block:
    - name: Authenticate with FreeIPA
      shell: "echo '{{ ipa_admin_password }}' | kinit admin"
      # no_log: true

    - name: Ensure DNS Forward and Reverse Zones exist
      command: "ipa dnszone-add {{ item }} --name-server={{ ipa_master_fqdn }}."
      loop: 
        - "{{ cloud_zone }}"      # e.g., example.ca
        - "{{ cloud_rev_zone }}"  # e.g., 0.168.192.in-addr.arpa.
        - "{{ nat_rev_zone }}"    # e.g., 0.0.10.in-addr.arpa.
      register: zone_create
      failed_when: 
        - zone_create.rc != 0 
        - "'already exists' not in zone_create.stderr"

    - name: Add A and PTR records for golden-base
      shell: |
        # 1. Forward A Record
        ipa dnsrecord-add {{ cloud_zone }} {{ vm_host }} --a-rec={{ VM_HOST_IP }}
        
        # 2. Reverse PTR Record (Uses the last octet of the VM_HOST_IP)
        ipa dnsrecord-add {{ cloud_rev_zone }} {{ VM_HOST_IP.split('.')[-1] }} --ptr-rec={{ vm_host }}.{{ cloud_zone }}.
      register: dns_reg
      failed_when: 
        - dns_reg.rc != 0 
        - "'already exists' not in dns_reg.stderr"