# role/ipa_setup/tasks/main.yml
- name: set ipa systems (masters)
  set_fact:
    ipa_master: "{{ groups['ca'][0] }}"
    ipa_master_ip: "{{ hostvars[groups['ca'][0]].ansible_host }}"
    ipa_ca_intermediate: "{{ groups['ca_intermediate'][0] }}"
    ipa_ca_intermediate_ip: "{{ hostvars[groups['ca_intermediate'][0]].ansible_host }}"
    ipa_helper: "{{ groups['helpers'][0] }}"
    ipa_helper_ip: "{{ hostvars[groups['helpers'][0]].ansible_host }}"
    vm_build_stage: "{{ vm_build_state }}"
  run_once: true
  delegate_to: localhost

- name: Check if ipa-server package is installed
  become: yes
  shell: "rpm -q ipa-server || true"
  register: ipa_pkg
  changed_when: false
  when:
    - "'helpers' in group_names"

- debug: msg="{{ ipa_pkg }}"
  when:
    - "'helpers' in group_names"

- debug: msg="group_names {{ group_names }}"
  when:
    - "'helpers' in group_names"


- name: Import IPA status check tasks
  import_tasks: check_ipa.yml
  when:
    - "'helpers' in group_names"
    - ipa_pkg.stdout is not search("not installed")

- debug: 
    msg:
      - "global_vm_build_state {{ global_vm_build_state}}"
      - "vm_build_state {{ vm_build_stage }}"

# role/ipa_setup/tasks/main.yml
- name: set ipa helpers
  block:
    - name: Addin IPA 
      debug: msg="{{ inventory_hostname }} ipa_role is helpers"

    - name: Include install.yml
      import_tasks: install.yml

    - name: Prep for ca helper
      import_tasks: ipa_ca_helpers.yml

  when: 
    - "'helpers' in group_names"
    - vm_build_state in ["scanned","non-compliant","compliant"]

- debug: 
    msg:
      - "global_vm_build_state {{ global_vm_build_state}}"
      - "vm_build_state {{ vm_build_stage }}"

- name: Secure final ipa host
  import_tasks: secops.yml
  when: 
    - "'helpers' in group_names"
    - vm_build_stage in ["scanned", "non-compliant", "compliant"]
  
- name: update global_vm_build_state
  set_fact:
    global_vm_build_state: "{{ vm_build_stage }}"
    vm_build_state: "{{ vm_build_stage }}"


