---
- name: Ensure base ansible directory exists
  file:
    path: "{{ cloud_helper_workdir }}/ansible"
    state: directory
    mode: "0755"

- name: Define base directory list
  set_fact:
    cloud_helper_base_dirs:
    - ""
    - "inventory"
    - "group_vars"
    - "host_vars"

- name: Ensure base directories exist
  file:
    path: "{{ cloud_helper_workdir }}/ansible/{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ cloud_helper_user }}"
    group: "{{ cloud_helper_user }}"
  loop: "{{ cloud_helper_base_dirs }}"

- name: Define role list
  set_fact:
    cloud_helper_roles:
      - ignition
      - vm_create
      - coreos_install
      - kubeadm_init
      - kubeadm_join
      - cluster_validate
      - helper_http

- name: Create base role directories
  file:
    path: "{{ cloud_helper_workdir }}/ansible/roles/{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ cloud_helper_user }}"
    group: "{{ cloud_helper_user }}"
  loop: "{{ cloud_helper_roles }}"

- name: Create standard subdirectories for each role
  file:
    path: "{{ cloud_helper_workdir }}/ansible/roles/{{ item.0 }}/{{ item.1 }}"
    state: directory
    mode: "0755"
    owner: "{{ cloud_helper_user }}"
    group: "{{ cloud_helper_user }}"
  loop: "{{ cloud_helper_roles | product(['defaults','handlers','tasks','templates','vars','scripts','files']) | list }}"


- name: Download Fedora CoreOS stable stream metadata
  become: yes
  become_user: "{{ cloud_helper_user }}"
  get_url:
    url: "https://builds.coreos.fedoraproject.org/streams/stable.json"
    dest: "/opt/cloud_helper/fcos/stable.json"
    mode: "0644"
  
- name: Ensure FCOS boot directories exist on KVM host
  delegate_to: "{{ VM_HOST }}"
  become: true
  file:
    path: "/var/lib/libvirt/boot"
    state: directory
    mode: "0775"
    owner: qemu
    group: qemu
  
- name: Ensure FCOS boot directories exist on KVM host
  delegate_to: "{{ VM_HOST }}"
  become: true
  file:
    path: "/var/lib/libvirt/boot/fcos"
    state: directory
    mode: "0775"
    owner: qemu
    group: qemu
  