- name: Create group_vars/all.yml file with variable references only
  copy:
    owner: "{{ cloud_helper_user }}"
    group: "{{ cloud_helper_user }}"
    dest: "{{ cloud_helper_workdir }}/ansible/group_vars/all.yml"
    mode: "0644"
    content: |
      {% raw %}
      ---
      cloud_helper_user: "{{ lookup('env','CLOUD_HELPER_USER') | default('cloud_helper') }}"
      cloud_helper_workdir: "{{ lookup('env','CLOUD_HELPER_WORKDIR') | default('/opt/cloud_helper') }}"

      fcos_image_url: "{{ lookup('env','FCOS_IMAGE_URL') }}"
      fcos_live_kernel_url: "{{ lookup('env','FCOS_LIVE_KERNEL_URL') }}"
      fcos_live_initramfs_url: "{{ lookup('env','FCOS_LIVE_INITRAMFS_URL') }}"
      fcos_live_rootfs_url: "{{ lookup('env','FCOS_LIVE_ROOTFS_URL') }}"

      kubernetes_version: "{{ lookup('env','KUBERNETES_VERSION') }}"
      cluster_name: "{{ lookup('env','CLUSTER_NAME') | default('k8s-cluster') }}"
      cluster_pod_cidr: "{{ lookup('env','CLUSTER_POD_CIDR') | default('10.244.0.0/16') }}"
      cluster_service_cidr: "{{ lookup('env','CLUSTER_SERVICE_CIDR') | default('10.96.0.0/12') }}"

      kvm_libvirt_uri: "{{ lookup('env','KVM_LIBVIRT_URI') | default('qemu:///system') }}"
      kvm_pool_name: "{{ lookup('env','KVM_POOL_NAME') | default('KVM_Pool') }}"
      kvm_network_cluster: "{{ lookup('env','KVM_NETWORK_CLUSTER') | default('br-cluster') }}"
      kvm_network_nat: "{{ lookup('env','KVM_NETWORK_NAT') | default('br-nat') }}"
      kvm_network_provisioning: "{{ lookup('env','KVM_NETWORK_PROVIDER') | default('br-provisioning') }}"
      helper_http_ip: "{{ lookup('env','helper_http_ip') | default('172.16.0.20') }}"

      ignition_version: "{{ lookup('env','IGNITION_VERSION') | default('3.4.0') }}"
      vm_name : "{{ lookup('env','VM_NAME') | default('k8s-node') }}"
      vm_cpu : "{{ lookup('env','VM_CPU') | default(4) }}"
      vm_ram_mb : "{{ lookup('env','VM_RAM_MB') | default(8192) }}"
      vm_disk_gb : "{{ lookup('env','VM_DISK_SIZE') | default(50) }}"
      kvm_host : "{{ lookup('env','VM_HOST') | default('kvmdc01.h') }}"

      {% endraw %}
