- name: Ensure ~/.ssh exists
  file:
    path: "/home/{{ cloud_helper_user }}/.ssh"
    state: directory
    mode: "0700"

- name: Generate new id_rsa keypair for automation
  openssh_keypair:
    path: "/home/{{ cloud_helper_user }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    owner: "{{ cloud_helper_user }}"
    group: "{{ cloud_helper_user }}"
    mode: "0600"
  register: new_keypair

- name: Read helper public key into variable
  slurp:
    src: "/home/{{ cloud_helper_user }}/.ssh/id_rsa.pub"
  register: helper_pubkey_raw

- name: Decode helper public key
  set_fact:
    helper_pubkey: "{{ helper_pubkey_raw.content | b64decode }}"

- name: Add helper public key to KVM host
  authorized_key:
    user: "{{ cloud_helper_user }}"
    state: present
    key: "{{ helper_pubkey }}"
  delegate_to: "{{ VM_HOST }}"

# - name: Ensure SSH config entry for KVM host
#   blockinfile:
#     path: "/home/{{ cloud_helper_user }}/.ssh/config"
#     create: yes
#     owner: "{{ cloud_helper_user }}"
#     group: "{{ cloud_helper_user }}"
#     mode: "0600"
#     block: |
#       Host {{ groups['kvm'][0] }} {{ groups['kvm'][0] }}.home.morinsoft.ca
#         HostName {{ hostvars[groups['kvm'][0]].ansible_host }}
#         User {{ cloud_helper_user }}
#         IdentityFile /home/{{ cloud_helper_user }}/.ssh/id_rsa
#         StrictHostKeyChecking accept-new
