---
- name: Clean up temporary ignition files on VM_HOST
  file:
    path: "{{ ignition_tmp }}/{{ item }}-config.ign"
    state: absent
  loop: "{{ node_list }}"
  loop_control:
    loop_var: item
  delegate_to: "{{ VM_HOST }}"
  become: true

- name: Remove local temporary ignition files
  file:
    path: "{{ ignition_tmp }}/{{ item }}-config.ign"
    state: absent
  loop: "{{ node_list }}"
  loop_control:
    loop_var: item
  run_once: true
  become: true
