---
- name: Ensure images directory exists on vm_host
  file:
    path: "{{ fcos_iso_local | dirname }}"
    state: directory
    mode: "0755"
  delegate_to: "{{ VM_HOST }}"
  run_once: true
  become: true

- name: Download FCOS ISO to vm_host if missing
  get_url:
    url: "{{ fcos_iso_url }}"
    dest: "{{ fcos_iso_local }}"
    mode: "0644"
    force: no
  delegate_to: "{{ VM_HOST }}"
  run_once: true
  become: true
