- name: Get MACs for VM
  delegate_to: "{{ VM_HOST }}"
  shell: |
    virsh domiflist {{ item }} | awk '/network/ {print $5}'
  register: vm_macs
  loop: "{{ node_list }}"
  loop_control:
    loop_var: item


- name: Write per-VM network config
  delegate_to: "{{ VM_HOST }}"
  copy:
    dest: "/var/lib/libvirt/images/{{ item }}/firstboot/netconfig.json"
    content: |
      {
        "hostname": "{{ hostvars[item].hostname }}",
        "interfaces": {
          "{{ hostvars[item].primary_mac }}": "{{ hostvars[item].primary_ip }}",
          "{{ hostvars[item].cloud_mac }}": "{{ hostvars[item].cloud_ip }}"
        }
      }
  loop: "{{ node_list }}"
  loop_control:
    loop_var: item
