---
- name: Ensure required packages are installed
  package:
    name:
      - coreos-installer
    state: present
  become: true
- debug: msg="fcos iso local {{ fcos_iso_local }} and dir {{ default_vm_disk_dir }}"
- name: Ensure images directory exists
  file:
    path: "{{ fcos_iso_local | dirname }}"
    state: directory
    mode: "0755"
  become: true

- name: Ensure default VM disk directory exists
  file:
    path: "{{ default_vm_disk_dir }}"
    state: directory
    mode: "0755"
  become: true
