---
- debug: msg="fcos_cloud_support_pubkey {{ fcos_cloud_support_pubkey | default('') }}"
- name: Ensure ignition staging directory exists
  delegate_to: "{{ VM_HOST }}"
  file:
    path: "{{ ignition_staging }}"
    state: directory
    mode: "0755"

- name: Ensure firstboot directory exists inside Ignition staging
  delegate_to: "{{ VM_HOST }}"
  file:
    path: "{{ ignition_staging }}{{item}}"
    state: directory
    mode: "0755"
  with_items:
    - "/var"
    - "/var/lib"
    - "/var/lib/firstboot"
    - "/etc"
    - "/etc/systemd"
    - "/etc/systemd/system"

- name: Copy firstboot files to VM_HOST
  delegate_to: "{{ VM_HOST }}"
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ignition_staging }}/var/lib/firstboot/{{ item }}"
    mode: "0644"
  loop:
    - "fcos-firstboot-net.sh"
    - "fcos-firstboot-net.service"

- name: Copy netconfig files to VM_HOST
  delegate_to: "{{ VM_HOST }}"
  copy:
    src: "{{ role_path }}/files/netconfig_{{ item }}.json"

    dest: "{{ ignition_staging }}/var/lib/firstboot/netconfig_{{ item }}.json"
    mode: "0644"
  loop: "{{ node_list }}"
  loop_control:
    loop_var: item

- name: Render Ignition file for each node on controller (inline Jinja via copy)
  delegate_to: "{{ VM_HOST }}"
  copy:
    dest: "{{ ignition_staging }}/{{ item }}-config.ign"
    mode: "0644"
    content: |
      {
        "ignition": { "version": "3.2.0" },

        "storage": {
          "files": [
            {
              "path": "/var/lib/firstboot/netconfig.json",
              "mode": 420,
              "contents": {
                "source": "data:text/plain;base64,{{ lookup('file', role_path + '/files/netconfig_' ~ item ~ '.json') | b64encode }}"
              }
            },
            {
              "path": "/var/lib/firstboot/fcos-firstboot-net.sh",
              "mode": 493,
              "contents": {
                "source": "data:text/plain;base64,{{ lookup('file', role_path + '/files/fcos-firstboot-net.sh') | b64encode }}"
              }
            },
            {
              "path": "/etc/systemd/system/fcos-firstboot-net.service",
              "mode": 420,
              "contents": {
                "source": "data:text/plain;base64,{{ lookup('file', role_path + '/files/fcos-firstboot-net.service') | b64encode }}"
              }
            }
          ]
        },

        "passwd": {
          "users": [
            {
              "name": "core",
              "sshAuthorizedKeys": [
                "{{ ignition_ssh_authorized_key | default('') | trim }}",
                "{{ fcos_cloud_support_pubkey | default('') | trim }}"
              ]
            }
          ]
        },
        file: {
          path: /var/lib/firstboot
          content: {
          {
            "hostname": "msrlv9mast01.cloud.home.morinsoft.ca",
            "interfaces": {
                  "52:54:00:df:81:c3": "192.168.100.31",
              "52:54:00:d6:ef:69": "10.0.0.31"
                }
          }
          }
        }
        "systemd": {
          "units": [
            {
              "name": "fcos-firstboot-net.service",
              "enabled": true
            }
          ]
        }
      }
  loop: "{{ node_list }}"
  loop_control:
    loop_var: item

  

  # run_once: false
  
