apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: nginx.home.morinsoft.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service # The name of your existing Nginx service
            port:
              number: 80
  - host: httpd.home.morinsoft.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpd-service # The name of your existing Httpd service
            port:
              number: 80