- name: Ensure TLS directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ cert_key_path | dirname }}"
    - "{{ cert_csr_path | dirname }}"
  delegate_to: helper

- name: Generate private key
  command: openssl genrsa -out {{ cert_key_path }} 4096
  args:
    creates: "{{ cert_key_path }}"
  delegate_to: helper
