- name: Read CSR from remote host
  slurp:
    src: "{{ cert_csr_path }}"
  register: csr_data

- name: Request IPA certificate
  freeipa.ansible_freeipa.ipacert:
    ipaadmin_principal: "{{ ipa_admin_principal }}"
    ipaadmin_password: "{{ ipa_admin_password }}"
    state: present
    principal: "{{ cert_principal }}"
    csr: "{{ csr_data.content | b64decode }}"
    outfile: "{{ cert_crt_path }}"

# - name: Request IPA certificate for helper
#   freeipa.ansible_freeipa.ipacert:
#     ipaadmin_principal: admin
#     ipaadmin_password: "{{ ipa_admin_password }}"
#     state: present
#     principal: "host/helper.{{ ipa_domain }}"
#     csr: "{{ lookup('file', '/etc/pki/tls/certs/helper.csr') }}"
#     outfile: "/etc/pki/tls/certs/helper.crt"
#   delegate_to: helper
#   run_once: true
