- name: Read CSR from remote host
  slurp:
    src: "{{ cert_csr_path }}"
  register: csr_data

- debug: msg="ipa_admin_principal={{ ipa_admin_principal }} and ipa_admin_password={{ ipa_admin_password }}"
# - name: Request IPA certificate
#   freeipa.ansible_freeipa.ipacert:
#     ipaadmin_principal: "{{ ipa_admin_principal }}"
#     ipaadmin_password: "{{ ipa_admin_password }}"
#     state: requested
#     principal: "{{ ipa_admin_principal }}"
#     csr: "{{ csr_data.content | b64decode }}"
#   register: cert_request

- name: Request IPA certificate
  freeipa.ansible_freeipa.ipacert:
    ipaadmin_principal: "{{ ipa_admin_principal }}"     # admin
    ipaadmin_password: "{{ ipa_admin_password }}"       # admin password
    state: requested
    principal: "host/{{ inventory_hostname }}.{{ ipa_domain }}"
    csr: "{{ csr_data.content | b64decode }}"
  register: cert_request


- name: Save certificate
  copy:
    content: "{{ cert_request.certificate.certificate[0] }}"
    dest: "{{ cert_crt_path }}"
    mode: '0644'
