# defaults/main.yml
---
vm_storage_pool: default
vm_disk_size: 30G
vm_memory_mb: 8192
vm_vcpus: 4
install_phase: true
nat_ip: "{{ lookup('env', 'nat_ip_device') | default('172.16.0.20')}}"


butane_output_dir: /srv/fcos/butane
masters: "{{ groups['control_nodes'] | default([]) }}"
workers: "{{ groups['worker_nodes'] | default([]) }}"
control_nodes: "{{ groups['control_nodes'] | default([]) }}"
worker_nodes: "{{ groups['worker_nodes'] | default([]) }}"
helper_node: "{{ (groups['helpers'] | default([])) | first }}"
helper_ip: "{{ hostvars[groups['helpers'][0]].ansible_host }}"
fcos_http_base_url: "https://{{ (groups['helpers'] | default([])) | first }}.{{ipa_domain}}/boot"
ignition_base_url: "https://{{ (groups['helpers'] | default([])) | first }}.{{ipa_domain}}/ignition"
rootfs_url: "https://{{ (groups['helpers'] | default([])) | first }}.{{ipa_domain}}/boot/rootfs.img"
fcos_iso_url: "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/43.20251120.3.0/x86_64/fedora-coreos-43.20251120.3.0-live-iso.x86_64.iso"
