---
# FCOS ISO and VM defaults
fcos_iso_url: "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/43.20251120.3.0/x86_64/fedora-coreos-43.20251120.3.0-live-iso.x86_64.iso"
fcos_iso_local: "/tmp/fcos-embed/fcos-base.iso"
fcos_iso_with_ign: "/var/lib/libvirt/images/fcos-with-ign.iso"
ignition_tmp: "/tmp"
# Default pulls SSH key from environment variable SECOPS_KEY if present
ignition_ssh_authorized_key: "{{ lookup('env','secops_key') | default('') }}"

# VM defaults used when per-node values are missing
default_vm_disk_dir: "/var/lib/libvirt/images"
default_vm_disk_size_gb: 30
default_vm_memory_mb: 4096
default_vm_vcpus: 2
vm_network: "default"
fcos_cloud_support_pubkey: "{{ fcos_cloud_support_pub_key }}"

# Control whether to use the community.libvirt.virt module or virt-install fallback
use_virt_module: true

# Inventory group names the role will read at runtime
controller_group: "control_nodes"
worker_group: "worker_nodes"
kvm_group: "kvm"
# Network address base (used to compute fallback IPs if hostvars missing)
cluster_network_base: "10.0.0."
default_network_base: "192.168.100."
cloud_zone: "{{ lookup('env', 'cloud_zone') }}"
cloud_id: "{{ lookup('env', 'cloud_id') | default('automator',true)}}"
ignition_staging: "/opt/fcos/ignition-staging"
ingress_ip: "{{ lookup('env', 'ingress_ip') }}"