---
- name: Install required orchestration packages
  package:
    name:
      - git
      - ansible-core
      - python3-libvirt
      - libvirt-client
      - libvirt-daemon
      - libvirt-daemon-driver-qemu
      - libvirt-daemon-config-network
      - libvirt-daemon-config-nwfilter
      - qemu-kvm
      - virt-install
      - nginx
      - wget
      - curl
      - jq
      - ipa-client
    state: present
