---
- debug: msg="fcos_root {{ fcos_root }} on to {{ web_root }}"
- name: Symlink FCOS dirs into web root
  file:
    src: "{{ fcos_root }}/{{ item.src }}"
    dest: "{{ web_root }}/{{ item.dest }}"
    state: link
  loop:
    - { src: 'butane',   dest: 'butane' }
    - { src: 'ignition', dest: 'ignition' }
    - { src: 'http',     dest: 'boot' }
    - { src: 'ipxe',     dest: 'ipxe' }
    - { src: 'ansible',  dest: 'ansible' }


# - name: Symlink FCOS dirs into web root
#   file:
#     src: "{{ fcos_root }}/ipxe/boot.ipxe
#     dest: "{{ web_root }}/boot.ipxe"
#     state: link
