---
- name: Validate HTTP access to kernel
  uri:
    url: "http://{{ nat_ip }}/boot/vmlinuz"
    method: HEAD
    status_code: 200
  register: fcos_kernel_check
  changed_when: false

- name: Validate HTTP access to iPXE script
  uri:
    url: "http://{{ nat_ip }}/ipxe/boot.ipxe"
    method: HEAD
    status_code: 200
  register: fcos_ipxe_check
  changed_when: false
