# ──────── STAGE: Build if needed ─────────
- name: Get current epoch time from localhost
  become: false
  shell: date +%s
  register: epoch_result
  delegate_to: localhost
  changed_when: false

- name: Set global epoch fact
  set_fact:
    global_epoch: "{{ epoch_result.stdout | int }}"
    vm_host: "{{ inventory_hostname_short }}"
  when: "'kvm' not in group_names"

- name: Set global epoch fact
  set_fact:
    global_epoch: "{{ epoch_result.stdout | int }}"
    vm_host: "golden-base"
  when: "'kvm' in group_names"

- name: Set VM shutdown poll start time
  set_fact:
    vm_shutdown_start: "{{ global_epoch }}"

# - name: Trigger build if needed
#   include_tasks: define_vms.yml
  # when: vm_stage_map[vm_host] in ['build', 'building']

- name: Calculate wait time in minutes
  set_fact:
    wait_time_to_shutdown_or_fail: "{{ ((build_loops | int) * 10 // 60) }}"

- name: Display wait time
  debug:
    msg: "Probe VM will wait up to {{ wait_time_to_shutdown_or_fail }} minutes before resuming to next tasks"

- name: Probe VM with virsh until VM powers down
  shell: |
    sudo virsh list --all | sed 's/shut off/shutdown/' | grep -i "^.*{{ vm_host }}.*" | awk '{print $NF}'
  register: vm_state
  delegate_to: "{{ VM_HOST_IP }}"
  failed_when: false
  changed_when: false
  until: vm_state.stdout_lines[-1] == "shutdown"
  retries: "{{ build_loops|int }}"
  delay: 10

# Clone only the hosts defined in the 'hahost' group in inventory
- name: Clone Load Balancer nodes from Golden Image
  delegate_to: "{{ VM_HOST_IP }}"
  command: >
    sudo virt-clone --original golden-base 
    --name {{ item }} 
    --file /var/lib/libvirt/images/{{ item }}.qcow2
  loop: "{{ groups['hahost'] }}"
  register: lb_clones
  # We ignore the error if the VM already exists, but fail on anything else
  failed_when: 
    - lb_clones.rc != 0 
    - "'already exists' not in lb_clones.stderr"

- name: Get Target MAC from Hypervisor for all LBs
  delegate_to: "{{ VM_HOST_IP }}"
  shell: "sudo virsh domiflist {{ item.split('.')[0] }} | grep 'default' | awk '{print $5}' | head -n1"
  register: mac_discovery
  loop: "{{ groups['hahost'] }}"

- debug:
    msg: "{{ mac_discovery.stdout }}"

