# ──────── STAGE: Build if needed ─────────
- name: Get current epoch time from localhost
  become: false
  shell: date +%s
  register: epoch_result
  delegate_to: localhost
  changed_when: false

- name: Set global epoch fact
  set_fact:
    global_epoch: "{{ epoch_result.stdout | int }}"
    vm_host: "{{ inventory_hostname_short }}"

- name: Set VM shutdown poll start time
  set_fact:
    vm_shutdown_start: "{{ global_epoch }}"

# - name: Trigger build if needed
#   include_tasks: define_vms.yml
  # when: vm_stage_map[vm_host] in ['build', 'building']

- name: Calculate wait time in minutes
  set_fact:
    wait_time_to_shutdown_or_fail: "{{ ((build_loops | int) * 10 // 60) }}"

- name: who am I
  command: whoami
  become: false
  register: whoami_out
- debug:
    msg: "Current user is {{ whoami_out.stdout }}"

- name: Probe VM with echo until vm shutdown
  # when: vm_stage_map[vm_host] in ['build', 'building'] and  vm_build_stage | trim != "present"
  # when: vm_stage_map[vm_host] in ['build', 'building'] and  vm_build_stage | trim != "present"
  shell: |
    #virsh -c qemu+ssh://{{ cloud_helper_user}}@{{ VM_HOST_IP}}/system 'list --all' 
    #| sed 's/shut off/shutdown/'  | grep -i "^.*{{ vm_host }}.*" | awk '{print $NF}'
    sudo virsh list --all | sed 's/shut off/shutdown/' | grep -i "^.*{{ vm_host }}.*" | awk '{print $NF}'
  register: vm_state
  become: yes
  vars:
  delegate_to: "{{ VM_HOST_IP }}"
  failed_when: false
  changed_when: false
  until: (vm_state.stdout | default('')) == "shutdown"
  retries: "{{ build_loops|int }}"
  delay: 10          # 10 seconds between attempts

