
- name: "Initialize Primary Master Cluster"
  delegate_to: localhost
  run_once: true
  shell: >
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR core@10.0.0.31 "sudo modprobe overlay && sudo modprobe br_netfilter; printf 'net.bridge.bridge-nf-call-iptables = 1\nnet.bridge.bridge-nf-call-ip6tables = 1\nnet.ipv4.ip_forward = 1' | sudo tee /etc/sysctl.d/k8s.conf; sudo sysctl --system; sudo systemctl disable --now firewalld; sudo dnf makecache; sudo dnf install -y cri-o kubeadm kubelet kubectl; sudo systemctl daemon-reload; sudo systemctl enable --now crio; sudo systemctl enable --now kubelet; if [ ! -f /etc/kubernetes/admin.conf ]; then sudo kubeadm init --control-plane-endpoint 'msrlv9mast01:6443' --upload-certs --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=10.0.0.31 --cri-socket unix:///var/run/crio/crio.sock --ignore-preflight-errors=Swap,SystemVerification; else echo 'ALREADY_INITIALIZED'; fi"
  register: init_result

- name: "Show Initialization Output"
  debug:
    msg: "{{ init_result.stdout_lines }}"
  run_once: true
- name: "Capture Join Commands"
  delegate_to: localhost
  run_once: true
  shell: |
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR \
    core@{{ hostvars[groups['control_nodes'][0]]['provision_ip'] }} << 'EOF'
    M_TOKEN=$(sudo kubeadm token create --print-join-command)
    CERT_KEY=$(sudo kubeadm init phase upload-certs --upload-certs | tail -1)
    echo "MASTER_JOIN=${M_TOKEN} --control-plane --certificate-key ${CERT_KEY}"
    echo "WORKER_JOIN=$(sudo kubeadm token create --print-join-command)"
    EOF
  register: join_cmds_raw

- name: show join_cmds_raw
  debug:
    msg: "{{ join_cmds_raw.stdout }}"

- name: "Set Global Join Facts"
  set_fact:
    master_join_cmd: "{{ join_cmds_raw.stdout_lines | select('match', '^MASTER_JOIN=') | first | replace('MASTER_JOIN=', '') }}"
    worker_join_cmd: "{{ join_cmds_raw.stdout_lines | select('match', '^WORKER_JOIN=') | first | replace('WORKER_JOIN=', '') }}"
  delegate_to: localhost
  delegate_facts: true
  run_once: true

- name: show *_join_cmd
  debug:
    msg: |
      MASTER_JOIN: "{{ master_join_cmd }}"
      WORKER_JOIN: "{{ worker_join_cmd }}"



