---
- name: Join Secondary Master to Control Plane
  become: true
  shell: "{{ hostvars['localhost']['master_join_cmd'] }}"
  args:
    creates: /etc/kubernetes/kubelet.conf

- name: Setup kubeconfig
  become: true
  file:
    path: "/home/core/.kube"
    state: directory
    owner: core
    group: core
# (Add copy admin.conf task here if needed for local kubectl)