- name: "Join Secondary Masters to Control Plane"
  delegate_to: localhost
  # Run this for secondary masters only
  when: inventory_hostname in groups['control_nodes'][1:] 
  shell: |
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    core@{{ provision_ip }} "sudo {{ hostvars['localhost']['master_join_cmd'] }}"