# - name: "Join Worker Nodes to Cluster"
#   delegate_to: localhost
#   when: inventory_hostname in groups['worker_nodes']
#   shell: |
#     ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
#     core@{{ provision_ip }} "sudo {{ hostvars['localhost']['worker_join_cmd'] }}"