---
- name: Unmount filesystems
  mount:
    path: "{{ item }}"
    state: unmounted
  loop:
    - "{{ build_root }}/mnt/boot"
    - "{{ build_root }}/mnt"

- name: Detach loop device
  command: losetup -d {{ loopdev.stdout }}

- name: Convert raw to qcow2
  command: >
    qemu-img convert -f raw -O qcow2
    {{ build_root }}/rocky-k8s-base.raw
    {{ output_dir }}/rocky-k8s-base.qcow2
  args:
    creates: "{{ output_dir }}/rocky-k8s-base.qcow2"
