- name: Run image prep tasks on builder
  import_tasks: prep.yml
  delegate_to: "{{ builder_host }}"
  become: true

- name: Run image build tasks on builder
  import_tasks: build.yml
  delegate_to: "{{ builder_host }}"
  become: true

- name: Run finalize tasks on builder
  import_tasks: finalize.yml
  delegate_to: "{{ builder_host }}"
  become: true

- name: Convert raw → qcow2 on builder
  import_tasks: convert.yml
  delegate_to: "{{ builder_host }}"
  become: true
