# - name: Switch to ansible_user
#   become: yes
#   # become_user: "{{ ansible_user }}"
- debug:
    msg: "Current node is {{ inventory_hostname }} in group(s) {{ group_names }}" 
- name: Build Rocky Linux base image
  block:
  - name: Build Rocky Linux base image
    import_tasks: 00_create_golden.yml
    delegate_to: "{{ VM_HOST_IP }}"
  
  - name: wait for power down
    import_tasks: 01_wait_for_shutdown.yml
    delegate_to: "{{ VM_HOST_IP }}"
  when: 
    - "'kvm' in group_names"


    # - name: fix url
    #   import_tasks: fix_url.yml
    #   delegate_to: localhost  

    # - name: Run image build tasks on builder
    #   import_tasks: build.yml
    #   delegate_to: localhost

    # - name: Run finalize tasks on builder
    #   import_tasks: finalize.yml
    #   delegate_to: localhost

    # - name: Convert raw → qcow2 on builder
    #   import_tasks: convert.yml
    #   delegate_to: localhost
