---
- name: "Parse mapping for {{ vm_mapping }}"
  set_fact:
    this_vm_name: "{{ (vm_mapping.split('='))[0] }}"
    this_vm_ip: "{{ (vm_mapping.split('='))[1] }}"

- name: "Wait for SSH to be fully ready on {{ this_vm_ip }}"
  delegate_to: localhost
  wait_for:
    host: "{{ this_vm_ip }}"
    port: 22
    state: started
    delay: 5
    timeout: 300

- name: "Configure networking for {{ this_vm_name }} via {{ this_vm_ip }}"
  delegate_to: localhost
  shell: |
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@{{ this_vm_ip }} << EOF
    {% if hostvars[this_vm_name]['provision_ip'] is defined %}
    sudo nmcli con modify enp2s0 ipv4.addresses {{ hostvars[this_vm_name]['provision_ip'] }}/24 ipv4.method manual
    sudo nmcli con up enp2s0
    {% endif %}
    {% if hostvars[this_vm_name]['provider_ip'] is defined %}
    sudo nmcli con modify enp3s0 ipv4.addresses {{ hostvars[this_vm_name]['provider_ip'] }}/24 ipv4.method manual
    sudo nmcli con up enp3s0
    {% endif %}
    EOF
  when: 
    - this_vm_name in groups['cluster_nodes']
    - this_vm_ip is defined and this_vm_ip | length > 0