---
# Ensure directories exist
- name: Ensure build directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ build_root }}"
    - "{{ build_root }}/rootfs"
    - "{{ build_root }}/mnt"
    - "{{ build_root }}/rootfs/etc/yum.repos.d"


- name: Copy all repo files from localhost into installroot
  become: true
  copy:
    src: "/etc/yum.repos.d/{{ item }}"
    dest: "{{ build_root }}/rootfs/etc/yum.repos.d/{{ item }}"
    mode: '0644'
  loop: "{{ lookup('fileglob', '/etc/yum.repos.d/*.repo', wantlist=True) | map('basename') | list }}"

###############################################################
# Refresh metadata inside installroot
###############################################################
- name: Clean metadata inside installroot
  command: dnf --installroot={{ build_root }}/rootfs clean all
  changed_when: false
