- name: Check if containerd binary is present
  ansible.builtin.command: which containerd
  register: containerd_bin_check
  failed_when: containerd_bin_check.rc != 0
  changed_when: false

- name: Check containerd systemd service status
  ansible.builtin.systemd:
    name: containerd
  register: containerd_service_status

- name: Assert containerd service is active
  ansible.builtin.assert:
    that:
      - containerd_service_status.status.ActiveState == "active"
    fail_msg: "containerd service is not active"
    success_msg: "containerd service is running"

- name: Check containerd socket exists
  ansible.builtin.stat:
    path: /run/containerd/containerd.sock
  register: containerd_socket

- name: Assert containerd socket is present
  ansible.builtin.assert:
    that:
      - containerd_socket.stat.exists
    fail_msg: "containerd socket not found"
    success_msg: "containerd socket is available"

- name: Get containerd version
  ansible.builtin.command: containerd --version
  register: containerd_version
  changed_when: false

- name: Display containerd version
  ansible.builtin.debug:
    msg: "containerd version: {{ containerd_version.stdout }}"
