---
- name: Compile Butane files into Ignition
  import_tasks: compile.yml
  tags:
    - "ignition compile"
  when: "'helpers' in group_names"


- name: Validate Ignition JSON files
  import_tasks: validate.yml
  tags:
    - "ignition validation"
