---
- name: Find Ignition files
  find:
    paths: "{{ ignition_output_dir }}"
    patterns: "*.ign"
  register: ign_files

- name: Validate Ignition JSON
  command: jq empty {{ item.path }}
  loop: "{{ ign_files.files }}"
  changed_when: false
  tags:
    - "**ignition validation**"
